//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompanyMAX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public int AgentID { get; set; }
        public int InsuranceCaseID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime date { get; set; }
        public int years { get; set; }
        public string sum { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Client Client { get; set; }
        public virtual InsuranceCase InsuranceCase { get; set; }
    }
}
