//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompanyMAX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCase()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int InsuranceTypeID { get; set; }
        public decimal costInYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual TypeOfInsurance TypeOfInsurance { get; set; }
    }
}
