//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompanyMAX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceCompanyMAXEntities : DbContext
    {
        private static InsuranceCompanyMAXEntities _context;
        public InsuranceCompanyMAXEntities()
            : base("name=InsuranceCompanyMAXEntities")
        {
        }
        public static InsuranceCompanyMAXEntities GetContext()
        {
            if (_context == null)
                _context = new InsuranceCompanyMAXEntities();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<InsuranceCase> InsuranceCases { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfInsurance> TypeOfInsurances { get; set; }
    }
}
